
#ansible playbook to create docker image. 
---
- name: Build an docker image 
  hosts: local
  connection: local
  remote_user: sureshjoshi 
  
  tasks:
    - name: build the image
      command: docker build -t sureshjoshi01/http_server:latest .

    - name: login  docker registry 
      command: docker login  --username sureshjoshi01  --password Rocky@007

    - name: push image to docker registry
      command: docker push sureshjoshi01/http_server:latest